#
# DO NOT EDIT THIS FILE!
# File automatically generated by
#   /home/gem5/gem5_new/build/X86/SConscript:596
#

buildEnv = {'KVM_ISA': 'x86', 'HAVE_KVM': True, 'HAVE_PERF_ATTR_EXCLUDE_HOST': 1, 'HAVE_FENV': True, 'HAVE_PNG': False, 'HAVE_POSIX_CLOCK': True, 'HAVE_VALGRIND': False, 'HAVE_DEPRECATED_NAMESPACE': 0, 'HAVE_HDF5': False, 'USE_SYSTEMC': True, 'HAVE_TUNTAP': True, 'HAVE_PROTOBUF': True, 'EXTRAS': '', 'BATCH': False, 'BATCH_CMD': 'qdo', 'M5_BUILD_CACHE': False, 'USE_EFENCE': False, 'BUILD_GPU': False, 'USE_NULL_ISA': False, 'USE_MIPS_ISA': False, 'USE_ARM_ISA': False, 'USE_ARM_FASTMODEL': False, 'PVLIB_HOME': '', 'PVLIB_FLAVOR': 'Linux64_GCC-7.3', 'MAXCORE_HOME': '', 'ARMLMD_LICENSE_FILE': '', 'ARMLMD_LICENSE_COUNT': 1, 'SIMGEN': '${MAXCORE_HOME}/bin/simgen', 'USE_SPARC_ISA': False, 'USE_RISCV_ISA': False, 'USE_X86_ISA': True, 'USE_POWER_ISA': False, 'NUMBER_BITS_PER_SET': '128', 'SLICC_HTML': False, 'USE_POSIX_CLOCK': True, 'TARGET_GPU_ISA': 'gcn3', 'PROTOCOL': 'MESI_Two_Level', 'USE_KVM': True}
