/**
 * DO NOT EDIT THIS FILE!
 * File automatically generated by
 *   build_tools/marshal.py:110
 */

#include "python/embedded.hh"

namespace gem5
{
namespace
{

const std::uint8_t embedded_module_data[] = {
    120,156,123,204,128,6,24,129,216,1,136,139,89,128,68,10,
    67,48,131,38,163,223,74,134,34,144,48,130,248,101,158,84,
    154,153,147,162,31,97,97,166,95,80,89,146,145,159,167,159,
    158,154,107,170,95,80,148,10,146,40,209,47,202,44,78,46,
    203,77,44,73,206,72,77,209,143,143,207,204,203,44,137,143,
    215,43,168,188,197,97,147,155,159,82,154,147,106,7,50,230,
    51,200,66,0,61,246,31,127,
};
EmbeddedPython embedded_module_info(
    "/home/gem5/gem5_new/src/python/gem5/prebuilt/riscvmatched/__init__.py",
    "gem5.prebuilt.riscvmatched",
    embedded_module_data,
    104,
    130);

} // anonymous namespace
} // namespace gem5
