#!/bin/bash
#
# 4-core 2x2 2D-mesh smoke test using the antipodal ping-pong workload.
# Verifies end-to-end: NoCInterface BFS routing, multi-hop NoC traversal, and
# the synthetic trace pipeline before scaling up to 16 cores.
#
# Usage:  ./test_pingpong_NoC_2dmesh_4core.sh <PROTOCOL>
#   e.g.  ./test_pingpong_NoC_2dmesh_4core.sh MSI

# Resolve paths relative to this script's location. Override either by
# exporting PROJECT_ROOT / BMs_ROOT / SIM_BIN before invoking the script.
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="${PROJECT_ROOT:-$SCRIPT_DIR}"
BMs_ROOT="${BMs_ROOT:-$PROJECT_ROOT/BMs}"
SIM_BIN="${SIM_BIN:-$PROJECT_ROOT/build/CMSpec_Simulator}"

cores=4
rows=2
cols=2

protocol="${1:-MSI}"

# Workload directory (assumes traces already generated by pingpong_synthetic).
workload_dir="${BMs_ROOT}/Synthetic/${cores}Cores/PingPong-antipodal"
logs="${workload_dir}/${protocol}_logs/"
mkdir -p "$logs"

core_ids=""
for ((ids=0; ids<$cores; ids++)); do
    core_ids+="${ids},"
done
LLC_id=64

# Router IDs: R(i,j) = 100 + i*cols + j  (i=row, j=col)
switch_ids=""
for ((s=0; s<$cores; s++)); do
    switch_ids+="$((100+s)),"
done

sim="${SIM_BIN}"
sim+=" -s PredictableDirectorySystem"
sim+=" -p 'workload_path(s)=${workload_dir}/'"
sim+=" -p 'logger_path(s)=${logs}'"
sim+=" -p 'cache_controller[*].protocol_type(s)=DIRECTORY_${protocol}'"
sim+=" -p 'cache_controller[*].fsm_filename(s)=${protocol}_directory'"
sim+=" -p 'llc_controller.protocol_type(s)=DIRECTORY_LLC_${protocol}'"
sim+=" -p 'llc_controller.fsm_filename(s)=${protocol}_LLC_directory'"
sim+=" -p 'num_cores(i)=${cores}'"
sim+=" -p 'llc_controller.arbiter_candidates_ids(vi)=${core_ids}'"
sim+=" -p 'llc_controller.processing_q_arbiter_candidates_ids(vi)=${core_ids}'"
sim+=" -p 'cache_controller[*].processing_q_arbiter_candidates_ids(vi)=${core_ids}'"

sim+=" -p 'm_main_memory.processing_q_arbiter_candidates_ids(vi)=${core_ids}'"
sim+=" -p 'm_main_memory.m_llc_id(i)=$LLC_id'",
sim+=" -p 'm_main_memory.m_memory_latency(i)=250'",

sim+=" -p 'bus.m_lower_level_ids(vi)=$LLC_id'",
sim+=" -p 'bus.interconnect_controller.candidates_id(vi)=${core_ids}'"

sim+=" -p 'cache_controller[*].processing_queue_size(i)=-1'"
sim+=" -p 'cache_controller[*].m_shared_memory_id(i)=$LLC_id'"
for ((id=0; id<$cores; id++)); do
    sim+=" -p 'cache_controller[$id].m_id(i)=$id'"
done
sim+=" -p 'llc_controller.processing_queue_size(i)=-1'"
sim+=" -p 'llc_controller.m_id(i)=$LLC_id'"

# ---- NoC topology: 2x2 2D mesh ----
sim+=" -p 'interconnect_type(s)=NoC'"
sim+=" -p 'interconnect.buffers_max_size(i)=128'"
sim+=" -p 'interconnect.interconnect_controller.m_candidates_ids(vi)=${core_ids}'"
sim+=" -p 'interconnect.component_ids(vi),${core_ids}$LLC_id,'"
sim+=" -p 'interconnect.switch_ids(vi),${switch_ids}'"

# Cores attached to their local router only.
for ((id=0; id<$cores; id++)); do
    local_router=$((100+id))
    sim+=" -p 'interconnect.connection_matrix[$id](vi),$id,$local_router,'"
done

# LLC at corner router R100.
sim+=" -p 'interconnect.connection_matrix[$cores](vi),$LLC_id,100,'"

# Routers in a 2x2 grid with N/S/E/W neighbors.
for ((k=0; k<$cores; k++)); do
    i=$((k / cols))
    j=$((k % cols))
    router_id=$((100+k))
    neighbors="$k,"           # local core
    if [ $k -eq 0 ]; then
        neighbors+="$LLC_id,"  # LLC at corner only
    fi
    # North
    if [ $i -gt 0 ]; then neighbors+="$((100+(i-1)*cols+j)),"; fi
    # South
    if [ $i -lt $((rows-1)) ]; then neighbors+="$((100+(i+1)*cols+j)),"; fi
    # East
    if [ $j -lt $((cols-1)) ]; then neighbors+="$((100+i*cols+(j+1))),"; fi
    # West
    if [ $j -gt 0 ]; then neighbors+="$((100+i*cols+(j-1))),"; fi
    idx=$((cores+1+k))
    sim+=" -p 'interconnect.connection_matrix[$idx](vi),$router_id,$neighbors'"
done

sim+=" -p 'cache_controller[*].m_data_handler.cache_size(i)=32768'"
sim+=" -p 'cache_controller[*].m_data_handler.m_ways_count(i)=4'"
sim+=" -p 'llc_controller.m_data_handler.cache_size(i)=4194304'"
sim+=" -p 'llc_controller.m_data_handler.m_ways_count(i)=8'"

sim+=" -p 'interconnect.interconnect_controller.arbiter_type(s)=FCFSArbiter'",
sim+=" -p 'bus.interconnect_controller.arbiter_type(s)=FCFSArbiter'",
sim+=" -p 'llc_controller.arbiter_type(s)=FCFSArbiter'",
sim+=" -p 'llc_controller.processing_q_arbiter_t(s)=NULL'",
sim+=" -p 'cache_controller[*].processing_q_arbiter_t(s)=NULL'",
sim+=" -p 'm_main_memory.processing_q_arbiter_t(s)=NULL'",
sim+=" -p 'system_arbiter(s)=FCFSArbiter'",
sim+=" -p 'RROF_size_limit(i)=24'",

date
echo "$sim"
eval "$sim"
echo "--- exit code: $? ---"
echo "--- Summary.csv (if produced) ---"
[ -f "${logs}/Summary.csv" ] && head -5 "${logs}/Summary.csv" || echo "  (not generated)"
