#!/usr/bin/env python3
"""configuration/**/*.csv -> generated/config_keys.tex

One longtable per configuration file, in a fixed order, with the key, its declared type
(the (i)/(s)/(vi)/(vs) suffix), the shipped value(s) and the '#' comment. A file's
'Extends,<Parent>' row becomes the table's subtitle. Run from anywhere.
"""
import csv, io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MANUAL = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(MANUAL))
CONF = os.path.join(REPO, "configuration")
OUT = os.path.join(MANUAL, "generated", "config_keys.tex")

TYPES = {"i": "int", "s": "string", "vi": "int list", "vs": "string list", "f": "float", "b": "bool"}


def tex(s):
    return (s.replace("\\", r"\textbackslash{}").replace("&", r"\&").replace("%", r"\%")
             .replace("$", r"\$").replace("#", r"\#").replace("_", r"\_").replace("{", r"\{")
             .replace("}", r"\}").replace("~", r"\textasciitilde{}").replace("^", r"\^{}")
             .replace("<", r"\textless{}").replace(">", r"\textgreater{}"))


def parse(path):
    rows, extends = [], None
    for cells in csv.reader(io.open(path, encoding="utf-8-sig", newline="")):
        cells = [c.strip() for c in cells]
        if not cells or not cells[0]:
            continue
        if cells[0] == "Extends":
            extends = cells[1] if len(cells) > 1 else ""
            continue
        if cells[0].startswith("#"):      # a comment row, not a key
            continue
        key = cells[0]
        m = re.match(r"^(.*)\(([a-z]+)\)$", key)
        name, typ = (m.group(1), m.group(2)) if m else (key, "")
        values, comment = [], ""
        for c in cells[1:]:
            if not c:
                continue
            if c.startswith("#"):
                comment = c[1:].strip(); break
            values.append(c)
        rows.append((name, TYPES.get(typ, typ), ", ".join(values), comment))
    return extends, rows


def files():
    order = []
    for d, _, fs in os.walk(CONF):
        for f in sorted(fs):
            if f.endswith(".csv") and f != "test_config.csv":
                order.append(os.path.join(d, f))
    # system configurations first (what a user edits), then the component defaults
    key = lambda p: (0 if "SystemConfigurations" in p else 1 if "CacheControllers" in p else 2 if "Interconnect" in p else 3, p)
    return sorted(order, key=key)


def main():
    out = ["% generated by tools/gen_config_tables.py -- do not edit", ""]
    total = 0
    for p in files():
        rel = os.path.relpath(p, REPO).replace("\\", "/")
        extends, rows = parse(p)
        total += len(rows)
        label = re.sub(r"[^a-z0-9]+", "-", rel.lower())
        out.append(r"\subsection*{\texttt{%s}}\label{cfg:%s}" % (tex(rel), label))
        if extends:
            out.append(r"\noindent\emph{Extends} \texttt{%s}; every key below overrides or adds to it." % tex(extends))
        out.append(r"\begin{longtable}{@{}>{\ttfamily\raggedright\arraybackslash}p{0.33\textwidth}p{0.07\textwidth}>{\raggedright\arraybackslash}p{0.19\textwidth}>{\raggedright\arraybackslash}p{0.33\textwidth}@{}}")
        out.append(r"\toprule \normalfont key & type & value & meaning \\ \midrule \endfirsthead")
        out.append(r"\toprule \normalfont key & type & value & meaning \\ \midrule \endhead")
        out.append(r"\bottomrule \endfoot")
        for name, typ, val, com in rows:
            # long dotted keys and value lists must be breakable inside a narrow column
            k = tex(name).replace(".", r".\allowbreak{}").replace(r"\_", r"\_\allowbreak{}").replace("[", r"\allowbreak{}[")
            v = tex(val).replace(", ", r",\allowbreak{} ").replace(r"\_", r"\_\allowbreak{}").replace("/", r"/\allowbreak{}")
            v = re.sub(r"(?<=[a-z])(?=[A-Z])", r"\\allowbreak{}", v)   # CamelCase class names
            v = re.sub(r"([0-9A-F]{8})(?=[0-9A-F])", r"\1\\allowbreak{}", v)  # long hex masks
            out.append(r"%s\index[cfg]{%s@\code{%s}} & %s & \texttt{%s} & %s \\" % (k, tex(name), tex(name), tex(typ), v, tex(com)))
        out.append(r"\end{longtable}")
        out.append("")
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print("gen_config_tables: %d files, %d keys -> %s" % (len(files()), total, os.path.relpath(OUT, MANUAL)))


if __name__ == "__main__":
    main()
