#!/usr/bin/env python3
"""Protocols_FSM/<name>.csv -> generated/fsm_<name>.tex

Each FSM CSV has four blocks: events, actions, states (each 'num, name' lists), then the
transition table whose header is 'State,stable,isDataValid,<event>...'. For each FSM
listed in FSMS this emits one landscape-friendly transition table (states as rows,
events as columns, cells 'actions/next') plus a compact three-column legend of the
numbered lists. Empty cells are left blank; a cell of just 'Fault/' is set in red.
"""
import csv, io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MANUAL = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(MANUAL))
FSM_DIR = os.path.join(REPO, "Protocols_FSM")
OUT_DIR = os.path.join(MANUAL, "generated")

FSMS = ["MSI_splitBus_snooping", "MSI_LLC", "MESI_splitBus_snooping", "MESI_LLC",
        "MOESI_splitBus_snooping", "MOESI_LLC", "MSI_directory", "MSI_LLC_directory"]


def tex(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")


def parse(path):
    rows = [[c.strip() for c in r] for r in csv.reader(io.open(path, encoding="utf-8-sig", newline=""))]
    lists, trans, header = {}, [], None
    block = None
    for r in rows:
        if not r or not any(r):
            continue
        head = r[0]
        if head in ("EventNum", "ActionNum", "StateNum"):
            block = {"EventNum": "events", "ActionNum": "actions", "StateNum": "states"}[head]
            lists[block] = []; continue
        if head == "State" and len(r) > 1 and r[1] == "stable":
            header = [c for c in r if c]; block = "trans"; continue
        if block == "trans":
            trans.append(r[:len(header)])
        elif block and re.match(r"^\d+$", head):
            lists[block].append((int(head), r[1]))
    return lists, header, trans


def cell(c):
    if not c:
        return ""
    if c in ("Fault/", "Fault"):
        return r"\textcolor{octred}{Fault}"
    return r"\texttt{%s}" % tex(c)


def emit(name):
    lists, header, trans = parse(os.path.join(FSM_DIR, name + ".csv"))
    events = header[3:]
    out = ["%% generated by tools/gen_fsm_tables.py from Protocols_FSM/%s.csv -- do not edit" % name, ""]
    # legend: events / actions / states side by side
    out.append(r"\begin{table}[htbp]\centering\footnotesize")
    out.append(r"\caption{\texttt{%s}: the numbered lists the table below is written in.}\label{fsm:%s:lists}" % (tex(name), name))
    out.append(r"\begin{tabular}{@{}lll@{}}\toprule events & actions & states \\ \midrule")
    n = max(len(lists.get(k, [])) for k in ("events", "actions", "states"))
    for i in range(n):
        col = []
        for k in ("events", "actions", "states"):
            L = lists.get(k, [])
            col.append(r"\texttt{%d\;%s}" % (L[i][0], tex(L[i][1])) if i < len(L) else "")
        out.append(" & ".join(col) + r" \\")
    out.append(r"\bottomrule\end{tabular}\end{table}")
    out.append("")
    # transition table on landscape pages, never scaled: each event column is as wide as its
    # longest single action, and a cell wraps after the '/' between actions. The font is the
    # largest that fits the landscape line; the table runs over several pages if it must.
    rows = []
    for r in trans:
        cells = r[3:] + [""] * (len(events) - len(r[3:]))
        rows.append((r[0], r[1], cells))
    def tokens(c):
        parts = [p for p in c.split("/")]
        return [p + "/" for p in parts[:-1]] + ([parts[-1]] if parts[-1] else [])
    longest = []
    for j in range(len(events)):
        L = 4
        for _, _, cells in rows:
            c = cells[j]
            if c in ("Fault/", "Fault"):
                L = max(L, 5)
            elif c:
                L = max(L, max(len(t) for t in tokens(c)))
        longest.append(L)
    state_len = max(len(st) for st, _, _ in rows)
    LINE_MM, SEP_MM = 253.0, 2.8                       # landscape text width; 2 x 4pt column padding
    for size, pt in ((r"\small", 9.0), (r"\footnotesize", 8.0), (r"\scriptsize", 7.0)):
        ch = 0.6 * pt * 0.3528                          # IBM Plex Mono advance width, mm
        widths = [max(L, 4) * ch + 1.5 for L in longest]   # + slack so neighbours never touch
        total = state_len * ch + SEP_MM + sum(w + SEP_MM for w in widths)
        if total <= LINE_MM:
            break
    spec = "@{}>{\\raggedright\\arraybackslash}p{%.1fmm}" % (state_len * ch) + "".join(
        ">{\\raggedright\\arraybackslash\\ttfamily}p{%.1fmm}" % w for w in widths) + "@{}"
    def wcell(c):
        if not c:
            return ""
        if c in ("Fault/", "Fault"):
            return r"\textcolor{octred}{Fault}"
        return r"\allowbreak{}".join(tex(t) for t in tokens(c))
    out.append(r"\begin{landscape}")
    out.append(r"{%s\setlength{\tabcolsep}{4pt}" % size)
    out.append(r"\begin{longtable}{%s}" % spec)
    out.append(r"\caption{\texttt{%s}: transitions as \texttt{actions/next\_state}; an empty cell ignores the event, \textcolor{octred}{Fault} aborts the run. \textbf{Bold} states are stable, \emph{italic} ones transient.}\label{fsm:%s}\\" % (tex(name), name))
    hdr = r"\toprule \textbf{state} & " + " & ".join(r"\rotatebox{60}{\texttt{%s}}" % tex(e) for e in events) + r" \\ \midrule"
    out.append(hdr + r" \endfirsthead")
    out.append(r"\multicolumn{%d}{@{}l}{\emph{\texttt{%s}, continued}} \\ " % (len(events) + 1, tex(name)) + hdr + r" \endhead")
    out.append(r"\bottomrule \endfoot")
    for st, stable, cells in rows:
        mark = r"\textbf{%s}" % tex(st) if stable == "1" else r"\emph{%s}" % tex(st)
        out.append(mark + " & " + " & ".join(wcell(c) for c in cells) + r" \\[2pt]")
    out.append(r"\end{longtable}}")
    out.append(r"\end{landscape}")
    p = os.path.join(OUT_DIR, "fsm_%s.tex" % name)
    io.open(p, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    return len(trans), len(events)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name in FSMS:
        if not os.path.exists(os.path.join(FSM_DIR, name + ".csv")):
            print("gen_fsm_tables: skip missing", name); continue
        ns, ne = emit(name)
        print("gen_fsm_tables: %-26s %2d states x %2d events" % (name, ns, ne))


if __name__ == "__main__":
    main()
