#!/usr/bin/env python3
"""Protocols_FSM/<name>.csv -> generated/fsm_<name>.tex

Each FSM CSV has four blocks: events, actions, states (each 'num, name' lists), then the
transition table whose header is 'State,stable,isDataValid,<event>...'. For each FSM
listed in FSMS this emits one landscape-friendly transition table (states as rows,
events as columns, cells 'actions/next') plus a compact three-column legend of the
numbered lists. Empty cells are left blank; a cell of just 'Fault/' is set in red.
"""
import csv, io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MANUAL = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(MANUAL))
FSM_DIR = os.path.join(REPO, "Protocols_FSM")
OUT_DIR = os.path.join(MANUAL, "generated")

FSMS = ["MSI_splitBus_snooping", "MSI_LLC", "MESI_splitBus_snooping", "MESI_LLC",
        "MOESI_splitBus_snooping", "MOESI_LLC", "MSI_directory", "MSI_LLC_directory"]


def tex(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")


def parse(path):
    rows = [[c.strip() for c in r] for r in csv.reader(io.open(path, encoding="utf-8-sig", newline=""))]
    lists, trans, header = {}, [], None
    block = None
    for r in rows:
        if not r or not any(r):
            continue
        head = r[0]
        if head in ("EventNum", "ActionNum", "StateNum"):
            block = {"EventNum": "events", "ActionNum": "actions", "StateNum": "states"}[head]
            lists[block] = []; continue
        if head == "State" and len(r) > 1 and r[1] == "stable":
            header = [c for c in r if c]; block = "trans"; continue
        if block == "trans":
            trans.append(r[:len(header)])
        elif block and re.match(r"^\d+$", head):
            lists[block].append((int(head), r[1]))
    return lists, header, trans


def cell(c):
    if not c:
        return ""
    if c in ("Fault/", "Fault"):
        return r"\textcolor{octred}{Fault}"
    return r"\texttt{%s}" % tex(c)


def emit(name):
    lists, header, trans = parse(os.path.join(FSM_DIR, name + ".csv"))
    events = header[3:]
    out = ["%% generated by tools/gen_fsm_tables.py from Protocols_FSM/%s.csv -- do not edit" % name, ""]
    # legend: events / actions / states side by side
    out.append(r"\begin{table}[htbp]\centering\footnotesize")
    out.append(r"\caption{\texttt{%s}: the numbered lists the table below is written in.}\label{fsm:%s:lists}" % (tex(name), name))
    out.append(r"\begin{tabular}{@{}lll@{}}\toprule events & actions & states \\ \midrule")
    n = max(len(lists.get(k, [])) for k in ("events", "actions", "states"))
    for i in range(n):
        col = []
        for k in ("events", "actions", "states"):
            L = lists.get(k, [])
            col.append(r"\texttt{%d\;%s}" % (L[i][0], tex(L[i][1])) if i < len(L) else "")
        out.append(" & ".join(col) + r" \\")
    out.append(r"\bottomrule\end{tabular}\end{table}")
    out.append("")
    # transition table: a landscape page, scaled down to the line width if it is wider
    out.append(r"\begin{landscape}")
    out.append(r"\begin{table}[p]\centering")
    out.append(r"\caption{\texttt{%s}: transitions as \texttt{actions/next\_state}; an empty cell ignores the event, \textcolor{octred}{Fault} aborts the run. \textbf{Bold} states are stable, \emph{italic} ones transient.}\label{fsm:%s}" % (tex(name), name))
    out.append(r"\begin{adjustbox}{max width=\linewidth}\small")
    out.append(r"\begin{tabular}{@{}l%s@{}}" % ("l" * len(events)))
    out.append(r"\toprule \textbf{state} & " + " & ".join(r"\rotatebox{60}{\texttt{%s}}" % tex(e) for e in events) + r" \\ \midrule")
    for r in trans:
        st, stable, valid = r[0], r[1], r[2]
        cells = r[3:] + [""] * (len(events) - len(r[3:]))
        mark = r"\textbf{%s}" % tex(st) if stable == "1" else r"\emph{%s}" % tex(st)
        out.append(mark + " & " + " & ".join(cell(c) for c in cells) + r" \\")
    out.append(r"\bottomrule\end{tabular}")
    out.append(r"\end{adjustbox}\end{table}")
    out.append(r"\end{landscape}")
    p = os.path.join(OUT_DIR, "fsm_%s.tex" % name)
    io.open(p, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    return len(trans), len(events)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name in FSMS:
        if not os.path.exists(os.path.join(FSM_DIR, name + ".csv")):
            print("gen_fsm_tables: skip missing", name); continue
        ns, ne = emit(name)
        print("gen_fsm_tables: %-26s %2d states x %2d events" % (name, ns, ne))


if __name__ == "__main__":
    main()
